### PR TITLE
Fix odd binding logic in treeview context menu.

### LINKED ISSUE #213: java.lang.NullPointerException in BooleanPropertyBase.java:164
## Error in DMDirc3

**java.lang.NullPointerException** in **BooleanPropertyBase.java:164**
Cannot bind to null

[View on Bugsnag](https://app.bugsnag.com/dmdirc/dmdirc3/errors/5c87a0887d213300190fc3ce?event_id=5c87a08800376784196b0000&i=gh&m=ci)

## Stacktrace

    BooleanPropertyBase.java:164 - javafx.beans.property.BooleanPropertyBase.bind

[View full stacktrace](https://app.bugsnag.com/dmdirc/dmdirc3/errors/5c87a0887d213300190fc3ce?event_id=5c87a08800376784196b0000&i=gh&m=ci)

*Created automatically via Bugsnag*

### PR DESCRIPTION
**Pull request by greboid**
Closes #213

### CODE REVIEW

File: src/main/kotlin/com/dmdirc/MainView.kt [hunk 1]
```diff
@@ -34,19 +34,25 @@ import kotlinx.coroutines.launch
...
     private val joinDialogProvider: () -> JoinDialog,
-    private val controller: MainContract.Controller
+    private val connection: ConnectionContract.Controller?
 ) : ContextMenu() {
+    private val connected = connection?.connected?.value ?: false
+    private val joinChannel = MenuItem(tr("Join Channel"))
+    private val disconnect = MenuItem(tr("Disconnect"))
+
+    override fun show() {
+        disconnect.visibleProperty().value = connected
```
Comment (csmith) [inline src/main/kotlin/com/dmdirc/MainView.kt]: Shouldn't we recompute the value of `connected` here?
